name: Tests

on: [push, pull_request]

jobs:
    js:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [6.x, 8.x, 10.x, 12.x]

        defaults:
            run:
                working-directory: ./js

        steps:

        - uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}

        - run: npm install -g npm@latest

        - run: npm install

        - run: npm test


